CREATE TABLE R (A INT, B INT, C INT, D INT, E INT, F INT);

CREATE TABLE R1 (A INT,	B INT, C INT);

CREATE TABLE R2 (D INT,	E INT,	F INT);

CREATE TABLE F (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));